### ISSUE TITLE
undefined reference to `sched_yield'

### ISSUE THREAD

**Issue by gyp8735abc** [robotn/gohook#5] opened 2019-09-18 03:30 UTC
I am getting an error when compiling robotgo. Why is this?
============================================

AppData\Local\Temp\go-build188103574\b044\_x003.o: In function `eb_port_create':
G:/go/src/github.com/robotn/gohook/chan/eb_chan.h:382: undefined reference to `sched_yield'
C:\Users\F1930235\AppData\Local\Temp\go-build188103574\b044\_x003.o: In function `eb_port_free':
G:/go/src/github.com/robotn/gohook/chan/eb_chan.h:350: undefined reference to `sched_yield'
G:/go/src/github.com/robotn/gohook/chan/eb_chan.h:341: undefined reference to `sched_yield'
C:\Users\F1930235\AppData\Local\Temp\go-build188103574\b044\_x003.o: In function `cleanup_ops':
G:/go/src/github.com/robotn/gohook/chan/eb_chan.h:858: undefined reference to `sched_yield'
G:/go/src/github.com/robotn/gohook/chan/eb_chan.h:858: undefined reference to `sched_yield'
C:\Users\F1930235\AppData\Local\Temp\go-build188103574\b044\_x003.o:G:/go/src/github.com/robotn/gohook/chan/eb_chan.h:643: more undefined references to `sched_yield' follow

**Comment by vcaesar** [comment] 2019-09-29 15:12
Closing is due to can't reproduce. Check the gcc environment and version.

**Closed by vcaesar** 2019-09-29 15:12 UTC
